env:
  global:
  - ENCRYPTION_LABEL: "deploy_github.enc"
  - COMMIT_AUTHOR_EMAIL: "git@einverne.info"
sudo: required
language: node_js
node_js:
  - stable
before_install:
  - export TZ='Asia/Shanghai'
  - npm install gitbook-cli -g
  - gitbook fetch 3.2.3

install:
  - gitbook install
script:
  - gitbook build .

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleaup: true
  github_token: $GITHUB_TOKEN
  keep-history: false
  local_dir: _book
  repo: einverne/gitbook-tutorial
  name: Ein Verne
  email: git@einverne.info
  on:
    branch: master

after_success:
  - ls -lh
