env:
  global:
  - ENCRYPTION_LABEL: "deploy_github.enc"
  - COMMIT_AUTHOR_EMAIL: "git@einverne.info"
  - GITBOOK_DIR: "static"
sudo: required
language: node_js
node_js:
  - stable
before_install:
  - export TZ='Asia/Shanghai'
  - npm install gitbook-cli -g
  - gitbook install
script:
  - gitbook build . $GITBOOK_DIR

branches:
  only:
    - master

deploy:
  provider: pages
  edge:
    branch: v1.8.47
  skip_cleaup: true
  github_token: $GITHUB_TOKEN
  local_dir: $GITBOOK_DIR
  repo: einverne/gitbook-tutorial
  name: Ein Verne
  email: git@einverne.info
  on:
    branch: master