env:
  global:
  - ENCRYPTION_LABEL: "deploy_github.enc"
  - COMMIT_AUTHOR_EMAIL: "git@einverne.info"
sudo: required
language: node_js
node_js:
  - stable
before_install:
  - export TZ='Asia/Shanghai'
  - npm install gitbook-cli -g
  - gitbook install
script:
  - gitbook build . out

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleaup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  name: Ein Verne
  email: git@einverne.info
  on:
    branch: master