env:
  global:
  - ENCRYPTION_LABEL: "deploy_github.enc"
  - COMMIT_AUTHOR_EMAIL: "git@einverne.info"
sudo: required
language: node_js
node_js:
  - stable
before_install:
  - export TZ='Asia/Shanghai'
  - npm install gitbook-cli -g
  - npm install svgexport -g
  - gitbook fetch 3.2.3
  - sudo apt-get update -qq
  - sudo -v && wget --no-check-certificate -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"

install:
  - gitbook install

before_script:
  - mkdir -p ~/.fonts/noto
  - mkdir -p ~/raw_fonts/{NotoSans-unhinted,NotoSansCJKsc-hinted,NotoSansCJKtc-hinted}
  - wget -P ~/raw_fonts https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip
  - unzip ~/raw_fonts/NotoSans-unhinted.zip -d ~/raw_fonts/NotoSans-unhinted
  - wget -P ~/raw_fonts https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKsc-hinted.zip
  - unzip ~/raw_fonts/NotoSansCJKsc-hinted.zip -d ~/raw_fonts/NotoSansCJKsc-hinted
  - wget -P ~/raw_fonts https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKtc-hinted.zip
  - unzip ~/raw_fonts/NotoSansCJKtc-hinted.zip -d ~/raw_fonts/NotoSansCJKtc-hinted


script:
  - mv -t ~/.fonts/noto ~/raw_fonts/NotoSansCJKsc-hinted/*-DemiLight.otf ~/raw_fonts/NotoSansCJKsc-hinted/*-Bold.otf ~/raw_fonts/NotoSansCJKsc-hinted/*-Black.otf
  - sudo fc-cache -f -v
  - gitbook pdf .
  - gitbook epub .
  - gitbook mobi .
  - rm ~/.fonts/noto/*.otf

  - gitbook build .

branches:
  only:
    - master

before_deploy:
  - tar czvf book_html.tar.gz _book/

deploy:
  provider: pages
  skip_cleaup: true
  github_token: $GITHUB_TOKEN
  keep-history: false
  local_dir: _book
  repo: einverne/gitbook-tutorial
  name: Ein Verne
  email: git@einverne.info
  target-branch: gh-pages
  on:
    branch: master

after_success:
  - ls -lh
